# Generated by Django 2.0.8 on 2018-11-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
