# Generated by Django 2.0.8 on 2018-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181116_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='BuyPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
