# Generated by Django 2.0.8 on 2018-11-29 11:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('order', '0003_auto_20181129_1126'),
        ('products', '0003_film_buyprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Product',
        ),
    ]
