# Generated by Django 2.0.8 on 2018-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181129_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Б', 'Боевик'), ('К', 'Комедия')], max_length=1, null=True),
        ),
    ]
