# Generated by Django 2.0.8 on 2018-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('A', 'Action'), ('C', 'Commedy')], max_length=1, null=True),
        ),
    ]
