# Generated by Django 2.0.8 on 2018-12-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181207_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Commedy', 'Commedy')], max_length=1, null=True),
        ),
    ]
