# Generated by Django 2.0.8 on 2018-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, upload_to='static/products/%Y/%m/%d'),
        ),
    ]
