# Generated by Django 2.0.8 on 2018-12-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181208_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='BuyPrice',
            new_name='PurchaisePrice',
        ),
    ]
