# Generated by Django 2.0.8 on 2018-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_film_buyprice'),
        ('order', '0002_auto_20181128_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete='Protect', to='products.Film')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
