# Generated by Django 2.0.8 on 2018-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181204_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cascade', related_name='order', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cascade', related_name='items', to='order.Order'),
        ),
    ]
