# Generated by Django 2.0.8 on 2018-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181207_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='flat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
