# Generated by Django 2.0.8 on 2018-12-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20181207_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Order Summary',
                'indexes': [],
                'proxy': True,
                'verbose_name_plural': 'Orders Summary',
            },
            bases=('order.order',),
        ),
    ]
