# Generated by Django 2.0.9 on 2018-12-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Amount', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Descr', models.TextField()),
                ('PurchaisePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Category', models.CharField(blank=True, choices=[('Action', 'Action'), ('Commedy', 'Commedy')], max_length=10, null=True)),
                ('Image', models.ImageField(blank=True, upload_to='static/products/%Y/%m/%d')),
            ],
        ),
    ]
