# Generated by Django 2.0.8 on 2018-11-16 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('proucts', models.ManyToManyField(blank=True, to='products.Film')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='Cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
