# Generated by Django 2.0.8 on 2018-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitty', models.PositiveIntegerField()),
                ('product', models.ManyToManyField(blank=True, to='products.Film')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='proucts',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cascade', to='cart.Entry'),
        ),
    ]
