# Generated by Django 2.0.8 on 2018-11-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0002_auto_20181116_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='quantitty',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='cart.Entry'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.AddField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cascade', to='products.Film'),
        ),
    ]
