# Generated by Django 2.0.8 on 2018-11-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20181116_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='entry',
            name='cart',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='cart.Cart'),
        ),
    ]
