# Generated by Django 2.0.8 on 2018-11-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20181116_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete='Cascade', to='cart.Entry'),
        ),
    ]
