# Generated by Django 2.0.8 on 2018-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20181116_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='entry',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='cart.Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.ForeignKey(null=True, on_delete='PROTECT', to='products.Film'),
        ),
    ]
