# Generated by Django 2.0.8 on 2018-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20181116_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='entry',
            field=models.OneToOneField(null=True, on_delete='CASCADE', to='cart.Entry'),
        ),
    ]
