# Generated by Django 2.0.8 on 2018-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20181116_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='cart',
            field=models.OneToOneField(null=True, on_delete='PROTECT', to='cart.Cart'),
        ),
    ]
