# Generated by Django 2.0.8 on 2018-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20181116_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cart',
            field=models.ForeignKey(null=True, on_delete='PROTECT', to='cart.Cart'),
        ),
    ]
