# Generated by Django 2.0.8 on 2018-12-08 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(on_delete='Protect', to=settings.AUTH_USER_MODEL),
        ),
    ]
