# Generated by Django 2.0.8 on 2018-12-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20181208_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'verbose_name_plural': 'Comments Summary',
                'verbose_name': 'Comment Summary',
            },
            bases=('comment.comment',),
        ),
    ]
