# Generated by Django 2.0.8 on 2018-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_commentsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=128),
        ),
    ]
