# Generated by Django 2.0.9 on 2018-12-14 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('rating', models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=2, default=1, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete='Protect', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete='Protect', related_name='comments', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CommentSummary',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Comment Summary',
                'verbose_name_plural': 'Comments Summary',
                'indexes': [],
            },
            bases=('comment.comment',),
        ),
    ]
